github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_64: linux_aarch64
  linux_aarch64: linux_64
test: native
channels:
  sources:
    - conda-forge
    - defaults
provider:
  linux_64: default
  linux_aarch64: default
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
